plugins:
  - rubocop-factory_bot
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

inherit_gem:
  rspec-sleeping_king_studios: config/rubocop-rspec.yml

AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  Include:
    - 'lib/**/*.rb'
    - 'spec/**/*.rb'
  Exclude:
    - 'tmp/**/*'
    - 'vendor/**/*'

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Layout/LineLength:
  AllowedPatterns:
    - '\A\s*#'
  Max: 80

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation
  IndentationWidth: ~

Metrics/BlockLength:
  Exclude:
    - 'lib/librum/components/rspec/deferred/**/*_examples.rb'
    - 'spec/**/*.rb'

Metrics/ModuleLength:
  Exclude:
    - 'lib/librum/components/rspec/deferred/**/*_examples.rb'
    - 'spec/**/*.rb'

Naming/RescuedExceptionsVariableName:
  PreferredName: exception

RSpec/BeNil:
  Enabled: false

RSpec/Eq:
  Enabled: false

RSpec/ExampleLength:
  Max: 10

RSpec/ExampleWording:
  Enabled: false

RSpec/HookArgument:
  EnforcedStyle: example

RSpec/IncludeExamples:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/NestedGroups:
  Max: 5

Style/ClassAndModuleChildren:
  # Checks the style of children definitions at classes and modules.
  #
  # Our preferred style is compact-plus-one, which does not match any of the
  # existing styles, so we disable this cop.
  Enabled: false
