require:
  - rubocop-rspec

inherit_gem:
  rspec-sleeping_king_studios: config/rubocop-rspec.yml

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Include:
    - 'lib/**/*.rb'
    - 'spec/**/*.rb'
  Exclude:
    - 'tmp/**/*'
    - 'vendor/**/*'

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Layout/LineLength:
  AllowedPatterns:
    - '\A\s*#'
  Max: 80

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation
  IndentationWidth: ~

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*.rb'

Naming/RescuedExceptionsVariableName:
  PreferredName: exception

RSpec/BeNil:
  Enabled: false

RSpec/Eq:
  Enabled: false

RSpec/ExampleLength:
  Max: 10

RSpec/ExampleWording:
  Enabled: false

RSpec/HookArgument:
  EnforcedStyle: example
