---
name: Librum::Components::Version::BUILD
parent_path: librum/components/version
slug: build
short_description: Build metadata.
value: nil
data_path: librum/components/version/build
metadata:
  api: private
version: "*"
