---
name: Librum::Components::Bulma::Base
slug: base
type: class
files:
- lib/librum/components/bulma/base.rb
parent_path: librum/components/bulma
short_description: Abstract base component for components using the Bulma CSS Framework.
class_methods:
- name: abstract?
  path: librum/components/bulma/base/c-abstract?
  slug: abstract?
  inherited: false
- name: build
  path: librum/components/base/c-build
  slug: build
  inherited: true
- name: option
  path: librum/components/base/c-option
  slug: option
  inherited: true
instance_attributes:
- name: options
  read: true
  write: false
  path: librum/components/options/i-options
  slug: options
  inherited: true
instance_methods:
- name: bulma_class_names
  path: librum/components/bulma/base/i-bulma-class-names
  slug: bulma-class-names
  inherited: false
- name: class_names
  path: librum/components/base/i-class-names
  slug: class-names
  inherited: true
- name: components
  path: librum/components/base/i-components
  slug: components
  inherited: true
- name: configuration
  path: librum/components/base/i-configuration
  slug: configuration
  inherited: true
- name: initialize
  path: librum/components/options/i-initialize
  slug: initialize
  inherited: true
- name: is_layout?
  path: librum/components/base/i-is-layout?
  slug: is-layout?
  inherited: true
data_path: librum/components/bulma/base
metadata:
  see:
  - label: https://bulma.io/
    path: https://bulma.io/
    text:
    type: link
constructor: true
direct_subclasses:
- name: Librum::Components::Bulma::Box
  slug: box
  path: librum/components/bulma/box
- name: Librum::Components::Bulma::Heading
  slug: heading
  path: librum/components/bulma/heading
- name: Librum::Components::Bulma::Icon
  slug: icon
  path: librum/components/bulma/icon
- name: Librum::Components::Bulma::Label
  slug: label
  path: librum/components/bulma/label
- name: Librum::Components::Bulma::Layouts::Page
  slug: page
  path: librum/components/bulma/layouts/page
- name: Librum::Components::Bulma::Layouts::Page::Footer
  slug: footer
  path: librum/components/bulma/layouts/page/footer
- name: Librum::Components::Bulma::Layouts::Page::Footer::Copyright
  slug: copyright
  path: librum/components/bulma/layouts/page/footer/copyright
- name: Librum::Components::Bulma::Layouts::Page::Header
  slug: header
  path: librum/components/bulma/layouts/page/header
- name: Librum::Components::Bulma::Layouts::Page::Header::Brand
  slug: brand
  path: librum/components/bulma/layouts/page/header/brand
- name: Librum::Components::Bulma::Layouts::Page::Header::Navbar
  slug: navbar
  path: librum/components/bulma/layouts/page/header/navbar
- name: Librum::Components::Bulma::Layouts::Page::Header::NavbarItem
  slug: navbar-item
  path: librum/components/bulma/layouts/page/header/navbar-item
- name: Librum::Components::Bulma::Link
  slug: link
  path: librum/components/bulma/link
inherited_classes:
- name: Librum::Components::Base
  slug: base
  path: librum/components/base
- name: ViewComponent::Base
  slug: base
version: "*"
