---
collections:
  classes:
    output: false
  constants:
    output: false
  methods:
    output: false
  modules:
    output: false
  namespaces:
    output: false
defaults:
- scope:
    path: ''
    type: 'pages'
  values:
    encoding: 'utf-8'
    layout: 'default'
    title: 'Librum::Components'
description: |
  Component library for Librum applications.
